---

- hosts: all
  tasks:
    - name: install initscripts
      package:
        name: initscripts
        state: present
      when: ansible_os_family == 'RedHat'

- hosts: all
  any_errors_fatal: true
  vars:
    vault_config:
      storage:
        file:
          path: /tmp/vault-data
      listener:
        tcp:
          address: "{{ '127.0.0.1' if ansible_virtualization_type == 'docker' else ansible_default_ipv4.address }}:8200"
          tls_disable: 1
  roles:
    - role: kostyrev.vault
      vault_validate_certs: "{{ false if ansible_virtualization_type == 'docker' else true }}"
