---
- name: reload systemd
  command: systemctl daemon-reload

- name: restart vault
  service:
    name: vault
    state: restarted
  when:
    - vault_service_enabled
    - vault_service_restart_on_update
